replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/frontend
  tag: "development-69b2d40"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
istio:
  enabled: true
  gateway:
    name: public-gateway
  virtualService:
    hosts:
      - "fitnest.az"
    paths:
      - /
resources:
  requests:
    cpu: 11m
    memory: 130Mi
  limits:
    cpu: 500m
    memory: 200Mi
env:
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: "https://dev-api.fitnest.az"
