# values.yaml for landing-frontend

replicaCount: 1
image:
  repository: ghcr.io/fitnest-code/landing-frontend
  tag: "development-1a5c15c"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
networkPolicy:
  enabled: true
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: dev.fitnest.az
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dev.fitnest.az
      secretName: fitnest-wildcard-tls
  backend:
    service:
      name: "" # Empty means use the chart's fullname (landing-frontend)
      port: 80
resources:
  requests:
    cpu: 11m
    memory: 130Mi
  limits:
    cpu: 500m
    memory: 200Mi
env:
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: "https://dev-api.fitnest.az"
