replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/frontend
  tag: "development-latest"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
istio:
  enabled: true
  gateway:
    name: public-gateway
  virtualService:
    hosts:
      - "fitnest.az"
    paths:
      - /
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: "https://dev-api.fitnest.az"
